//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ObtenerPesoSAP.ValidaTransporte {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://cydsa.com/PL/TM/TM101/Receiver/WebServices/PesoVehiculo_Consulta", ConfigurationName="ValidaTransporte.SI_OS_Consulta_Transporte")]
    public interface SI_OS_Consulta_Transporte {
        
        // CODEGEN: Generating message contract since the operation SI_OS_Consulta_Transporte is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="http://sap.com/xi/WebService/soap1.1", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        ObtenerPesoSAP.ValidaTransporte.SI_OS_Consulta_TransporteResponse SI_OS_Consulta_Transporte(ObtenerPesoSAP.ValidaTransporte.SI_OS_Consulta_TransporteRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://sap.com/xi/WebService/soap1.1", ReplyAction="*")]
        System.Threading.Tasks.Task<ObtenerPesoSAP.ValidaTransporte.SI_OS_Consulta_TransporteResponse> SI_OS_Consulta_TransporteAsync(ObtenerPesoSAP.ValidaTransporte.SI_OS_Consulta_TransporteRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://cydsa.com/PL/TM/TM101/Receiver/WebServices/PesoVehiculo_Consulta")]
    public partial class DT_Consulta_Tranporte : object, System.ComponentModel.INotifyPropertyChanged {
        
        private DT_Consulta_TranporteData dataField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public DT_Consulta_TranporteData data {
            get {
                return this.dataField;
            }
            set {
                this.dataField = value;
                this.RaisePropertyChanged("data");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://cydsa.com/PL/TM/TM101/Receiver/WebServices/PesoVehiculo_Consulta")]
    public partial class DT_Consulta_TranporteData : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string numero_TransporteField;
        
        private string centro_LogisticoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string Numero_Transporte {
            get {
                return this.numero_TransporteField;
            }
            set {
                this.numero_TransporteField = value;
                this.RaisePropertyChanged("Numero_Transporte");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string Centro_Logistico {
            get {
                return this.centro_LogisticoField;
            }
            set {
                this.centro_LogisticoField = value;
                this.RaisePropertyChanged("Centro_Logistico");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://cydsa.com/PL/TM/TM101/Receiver/WebServices/PesoVehiculo_Consulta")]
    public partial class DT_Consulta_Tranporte_Resp : object, System.ComponentModel.INotifyPropertyChanged {
        
        private DT_Consulta_Tranporte_RespItem[] oPTIONSField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public DT_Consulta_Tranporte_RespItem[] OPTIONS {
            get {
                return this.oPTIONSField;
            }
            set {
                this.oPTIONSField = value;
                this.RaisePropertyChanged("OPTIONS");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://cydsa.com/PL/TM/TM101/Receiver/WebServices/PesoVehiculo_Consulta")]
    public partial class DT_Consulta_Tranporte_RespItem : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string typeField;
        
        private string responseField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string Type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
                this.RaisePropertyChanged("Type");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string Response {
            get {
                return this.responseField;
            }
            set {
                this.responseField = value;
                this.RaisePropertyChanged("Response");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SI_OS_Consulta_TransporteRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://cydsa.com/PL/TM/TM101/Receiver/WebServices/PesoVehiculo_Consulta", Order=0)]
        public ObtenerPesoSAP.ValidaTransporte.DT_Consulta_Tranporte MT_Consulta_Tranporte;
        
        public SI_OS_Consulta_TransporteRequest() {
        }
        
        public SI_OS_Consulta_TransporteRequest(ObtenerPesoSAP.ValidaTransporte.DT_Consulta_Tranporte MT_Consulta_Tranporte) {
            this.MT_Consulta_Tranporte = MT_Consulta_Tranporte;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SI_OS_Consulta_TransporteResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://cydsa.com/PL/TM/TM101/Receiver/WebServices/PesoVehiculo_Consulta", Order=0)]
        public ObtenerPesoSAP.ValidaTransporte.DT_Consulta_Tranporte_Resp MT_Consulta_Tranporte_Resp;
        
        public SI_OS_Consulta_TransporteResponse() {
        }
        
        public SI_OS_Consulta_TransporteResponse(ObtenerPesoSAP.ValidaTransporte.DT_Consulta_Tranporte_Resp MT_Consulta_Tranporte_Resp) {
            this.MT_Consulta_Tranporte_Resp = MT_Consulta_Tranporte_Resp;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface SI_OS_Consulta_TransporteChannel : ObtenerPesoSAP.ValidaTransporte.SI_OS_Consulta_Transporte, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SI_OS_Consulta_TransporteClient : System.ServiceModel.ClientBase<ObtenerPesoSAP.ValidaTransporte.SI_OS_Consulta_Transporte>, ObtenerPesoSAP.ValidaTransporte.SI_OS_Consulta_Transporte {
        
        public SI_OS_Consulta_TransporteClient() {
        }
        
        public SI_OS_Consulta_TransporteClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SI_OS_Consulta_TransporteClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SI_OS_Consulta_TransporteClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SI_OS_Consulta_TransporteClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ObtenerPesoSAP.ValidaTransporte.SI_OS_Consulta_TransporteResponse ObtenerPesoSAP.ValidaTransporte.SI_OS_Consulta_Transporte.SI_OS_Consulta_Transporte(ObtenerPesoSAP.ValidaTransporte.SI_OS_Consulta_TransporteRequest request) {
            return base.Channel.SI_OS_Consulta_Transporte(request);
        }
        
        public ObtenerPesoSAP.ValidaTransporte.DT_Consulta_Tranporte_Resp SI_OS_Consulta_Transporte(ObtenerPesoSAP.ValidaTransporte.DT_Consulta_Tranporte MT_Consulta_Tranporte) {
            ObtenerPesoSAP.ValidaTransporte.SI_OS_Consulta_TransporteRequest inValue = new ObtenerPesoSAP.ValidaTransporte.SI_OS_Consulta_TransporteRequest();
            inValue.MT_Consulta_Tranporte = MT_Consulta_Tranporte;
            ObtenerPesoSAP.ValidaTransporte.SI_OS_Consulta_TransporteResponse retVal = ((ObtenerPesoSAP.ValidaTransporte.SI_OS_Consulta_Transporte)(this)).SI_OS_Consulta_Transporte(inValue);
            return retVal.MT_Consulta_Tranporte_Resp;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ObtenerPesoSAP.ValidaTransporte.SI_OS_Consulta_TransporteResponse> ObtenerPesoSAP.ValidaTransporte.SI_OS_Consulta_Transporte.SI_OS_Consulta_TransporteAsync(ObtenerPesoSAP.ValidaTransporte.SI_OS_Consulta_TransporteRequest request) {
            return base.Channel.SI_OS_Consulta_TransporteAsync(request);
        }
        
        public System.Threading.Tasks.Task<ObtenerPesoSAP.ValidaTransporte.SI_OS_Consulta_TransporteResponse> SI_OS_Consulta_TransporteAsync(ObtenerPesoSAP.ValidaTransporte.DT_Consulta_Tranporte MT_Consulta_Tranporte) {
            ObtenerPesoSAP.ValidaTransporte.SI_OS_Consulta_TransporteRequest inValue = new ObtenerPesoSAP.ValidaTransporte.SI_OS_Consulta_TransporteRequest();
            inValue.MT_Consulta_Tranporte = MT_Consulta_Tranporte;
            return ((ObtenerPesoSAP.ValidaTransporte.SI_OS_Consulta_Transporte)(this)).SI_OS_Consulta_TransporteAsync(inValue);
        }
    }
}
