//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ObtenerPesoSAP.DocEntrega {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://cydsa.com/PL/TM/TM101/Receiver/WebServices/PesoVehiculo_ConsultaNumCarga", ConfigurationName="DocEntrega.SI_OS_Consulta_NumCarga")]
    public interface SI_OS_Consulta_NumCarga {
        
        // CODEGEN: Generating message contract since the operation SI_OS_Consulta_NumCarga is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="http://sap.com/xi/WebService/soap1.1", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        ObtenerPesoSAP.DocEntrega.SI_OS_Consulta_NumCargaResponse SI_OS_Consulta_NumCarga(ObtenerPesoSAP.DocEntrega.SI_OS_Consulta_NumCargaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://sap.com/xi/WebService/soap1.1", ReplyAction="*")]
        System.Threading.Tasks.Task<ObtenerPesoSAP.DocEntrega.SI_OS_Consulta_NumCargaResponse> SI_OS_Consulta_NumCargaAsync(ObtenerPesoSAP.DocEntrega.SI_OS_Consulta_NumCargaRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://cydsa.com/PL/TM/TM101/Receiver/WebServices/PesoVehiculo_ConsultaNumCarga")]
    public partial class DT_Consulta_NumCarga : object, System.ComponentModel.INotifyPropertyChanged {
        
        private DT_Consulta_NumCargaData dataField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public DT_Consulta_NumCargaData data {
            get {
                return this.dataField;
            }
            set {
                this.dataField = value;
                this.RaisePropertyChanged("data");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://cydsa.com/PL/TM/TM101/Receiver/WebServices/PesoVehiculo_ConsultaNumCarga")]
    public partial class DT_Consulta_NumCargaData : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string numero_TransporteField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string Numero_Transporte {
            get {
                return this.numero_TransporteField;
            }
            set {
                this.numero_TransporteField = value;
                this.RaisePropertyChanged("Numero_Transporte");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://cydsa.com/PL/TM/TM101/Receiver/WebServices/PesoVehiculo_ConsultaNumCarga")]
    public partial class DT_Consulta_NumCarga_Resp : object, System.ComponentModel.INotifyPropertyChanged {
        
        private DT_Consulta_NumCarga_RespOPTIONS oPTIONSField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public DT_Consulta_NumCarga_RespOPTIONS OPTIONS {
            get {
                return this.oPTIONSField;
            }
            set {
                this.oPTIONSField = value;
                this.RaisePropertyChanged("OPTIONS");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://cydsa.com/PL/TM/TM101/Receiver/WebServices/PesoVehiculo_ConsultaNumCarga")]
    public partial class DT_Consulta_NumCarga_RespOPTIONS : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string typeField;
        
        private DT_Consulta_NumCarga_RespOPTIONSItem[] itemField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string Type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
                this.RaisePropertyChanged("Type");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public DT_Consulta_NumCarga_RespOPTIONSItem[] item {
            get {
                return this.itemField;
            }
            set {
                this.itemField = value;
                this.RaisePropertyChanged("item");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://cydsa.com/PL/TM/TM101/Receiver/WebServices/PesoVehiculo_ConsultaNumCarga")]
    public partial class DT_Consulta_NumCarga_RespOPTIONSItem : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string responseField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string Response {
            get {
                return this.responseField;
            }
            set {
                this.responseField = value;
                this.RaisePropertyChanged("Response");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SI_OS_Consulta_NumCargaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://cydsa.com/PL/TM/TM101/Receiver/WebServices/PesoVehiculo_ConsultaNumCarga", Order=0)]
        public ObtenerPesoSAP.DocEntrega.DT_Consulta_NumCarga MT_Consulta_NumCarga;
        
        public SI_OS_Consulta_NumCargaRequest() {
        }
        
        public SI_OS_Consulta_NumCargaRequest(ObtenerPesoSAP.DocEntrega.DT_Consulta_NumCarga MT_Consulta_NumCarga) {
            this.MT_Consulta_NumCarga = MT_Consulta_NumCarga;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SI_OS_Consulta_NumCargaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://cydsa.com/PL/TM/TM101/Receiver/WebServices/PesoVehiculo_ConsultaNumCarga", Order=0)]
        public ObtenerPesoSAP.DocEntrega.DT_Consulta_NumCarga_Resp MT_Consulta_NumCarga_Resp;
        
        public SI_OS_Consulta_NumCargaResponse() {
        }
        
        public SI_OS_Consulta_NumCargaResponse(ObtenerPesoSAP.DocEntrega.DT_Consulta_NumCarga_Resp MT_Consulta_NumCarga_Resp) {
            this.MT_Consulta_NumCarga_Resp = MT_Consulta_NumCarga_Resp;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface SI_OS_Consulta_NumCargaChannel : ObtenerPesoSAP.DocEntrega.SI_OS_Consulta_NumCarga, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SI_OS_Consulta_NumCargaClient : System.ServiceModel.ClientBase<ObtenerPesoSAP.DocEntrega.SI_OS_Consulta_NumCarga>, ObtenerPesoSAP.DocEntrega.SI_OS_Consulta_NumCarga {
        
        public SI_OS_Consulta_NumCargaClient() {
        }
        
        public SI_OS_Consulta_NumCargaClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SI_OS_Consulta_NumCargaClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SI_OS_Consulta_NumCargaClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SI_OS_Consulta_NumCargaClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ObtenerPesoSAP.DocEntrega.SI_OS_Consulta_NumCargaResponse ObtenerPesoSAP.DocEntrega.SI_OS_Consulta_NumCarga.SI_OS_Consulta_NumCarga(ObtenerPesoSAP.DocEntrega.SI_OS_Consulta_NumCargaRequest request) {
            return base.Channel.SI_OS_Consulta_NumCarga(request);
        }
        
        public ObtenerPesoSAP.DocEntrega.DT_Consulta_NumCarga_Resp SI_OS_Consulta_NumCarga(ObtenerPesoSAP.DocEntrega.DT_Consulta_NumCarga MT_Consulta_NumCarga) {
            ObtenerPesoSAP.DocEntrega.SI_OS_Consulta_NumCargaRequest inValue = new ObtenerPesoSAP.DocEntrega.SI_OS_Consulta_NumCargaRequest();
            inValue.MT_Consulta_NumCarga = MT_Consulta_NumCarga;
            ObtenerPesoSAP.DocEntrega.SI_OS_Consulta_NumCargaResponse retVal = ((ObtenerPesoSAP.DocEntrega.SI_OS_Consulta_NumCarga)(this)).SI_OS_Consulta_NumCarga(inValue);
            return retVal.MT_Consulta_NumCarga_Resp;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ObtenerPesoSAP.DocEntrega.SI_OS_Consulta_NumCargaResponse> ObtenerPesoSAP.DocEntrega.SI_OS_Consulta_NumCarga.SI_OS_Consulta_NumCargaAsync(ObtenerPesoSAP.DocEntrega.SI_OS_Consulta_NumCargaRequest request) {
            return base.Channel.SI_OS_Consulta_NumCargaAsync(request);
        }
        
        public System.Threading.Tasks.Task<ObtenerPesoSAP.DocEntrega.SI_OS_Consulta_NumCargaResponse> SI_OS_Consulta_NumCargaAsync(ObtenerPesoSAP.DocEntrega.DT_Consulta_NumCarga MT_Consulta_NumCarga) {
            ObtenerPesoSAP.DocEntrega.SI_OS_Consulta_NumCargaRequest inValue = new ObtenerPesoSAP.DocEntrega.SI_OS_Consulta_NumCargaRequest();
            inValue.MT_Consulta_NumCarga = MT_Consulta_NumCarga;
            return ((ObtenerPesoSAP.DocEntrega.SI_OS_Consulta_NumCarga)(this)).SI_OS_Consulta_NumCargaAsync(inValue);
        }
    }
}
