//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ObtenerPesoSAP.PartidasMateriales {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://cydsa.com/PL/TM/TM101/Sender/WebServices/PesoVehiculo_ConsultaEntrega", ConfigurationName="PartidasMateriales.SI_OA_TM101_Consulta_Entrega")]
    public interface SI_OA_TM101_Consulta_Entrega {
        
        // CODEGEN: Generating message contract since the operation SI_OA_TM101_Consulta_Entrega is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="http://sap.com/xi/WebService/soap1.1", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        ObtenerPesoSAP.PartidasMateriales.SI_OA_TM101_Consulta_EntregaResponse SI_OA_TM101_Consulta_Entrega(ObtenerPesoSAP.PartidasMateriales.SI_OA_TM101_Consulta_EntregaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://sap.com/xi/WebService/soap1.1", ReplyAction="*")]
        System.Threading.Tasks.Task<ObtenerPesoSAP.PartidasMateriales.SI_OA_TM101_Consulta_EntregaResponse> SI_OA_TM101_Consulta_EntregaAsync(ObtenerPesoSAP.PartidasMateriales.SI_OA_TM101_Consulta_EntregaRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://cydsa.com/PL/TM/TM101/Sender/WebServices/PesoVehiculo_ConsultaEntrega")]
    public partial class DT_TM101_Consulta_Entrega_Req : object, System.ComponentModel.INotifyPropertyChanged {
        
        private DT_TM101_Consulta_Entrega_ReqItem itemField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public DT_TM101_Consulta_Entrega_ReqItem item {
            get {
                return this.itemField;
            }
            set {
                this.itemField = value;
                this.RaisePropertyChanged("item");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://cydsa.com/PL/TM/TM101/Sender/WebServices/PesoVehiculo_ConsultaEntrega")]
    public partial class DT_TM101_Consulta_Entrega_ReqItem : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string dELIV_NUMBField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string DELIV_NUMB {
            get {
                return this.dELIV_NUMBField;
            }
            set {
                this.dELIV_NUMBField = value;
                this.RaisePropertyChanged("DELIV_NUMB");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://cydsa.com/PL/TM/TM101/Sender/WebServices/PesoVehiculo_ConsultaEntrega")]
    public partial class DT_TM101_Consulta_Entrega_Resp : object, System.ComponentModel.INotifyPropertyChanged {
        
        private DT_TM101_Consulta_Entrega_RespItem[] eT_DELIVERY_ITEMField;
        
        private DT_TM101_Consulta_Entrega_RespItem1[] rETURNField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public DT_TM101_Consulta_Entrega_RespItem[] ET_DELIVERY_ITEM {
            get {
                return this.eT_DELIVERY_ITEMField;
            }
            set {
                this.eT_DELIVERY_ITEMField = value;
                this.RaisePropertyChanged("ET_DELIVERY_ITEM");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public DT_TM101_Consulta_Entrega_RespItem1[] RETURN {
            get {
                return this.rETURNField;
            }
            set {
                this.rETURNField = value;
                this.RaisePropertyChanged("RETURN");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://cydsa.com/PL/TM/TM101/Sender/WebServices/PesoVehiculo_ConsultaEntrega")]
    public partial class DT_TM101_Consulta_Entrega_RespItem : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string pOSNRField;
        
        private string mATNRField;
        
        private string aRKTXField;
        
        private string lFIMGField;
        
        private string mEINSField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string POSNR {
            get {
                return this.pOSNRField;
            }
            set {
                this.pOSNRField = value;
                this.RaisePropertyChanged("POSNR");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string MATNR {
            get {
                return this.mATNRField;
            }
            set {
                this.mATNRField = value;
                this.RaisePropertyChanged("MATNR");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string ARKTX {
            get {
                return this.aRKTXField;
            }
            set {
                this.aRKTXField = value;
                this.RaisePropertyChanged("ARKTX");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string LFIMG {
            get {
                return this.lFIMGField;
            }
            set {
                this.lFIMGField = value;
                this.RaisePropertyChanged("LFIMG");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string MEINS {
            get {
                return this.mEINSField;
            }
            set {
                this.mEINSField = value;
                this.RaisePropertyChanged("MEINS");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://cydsa.com/PL/TM/TM101/Sender/WebServices/PesoVehiculo_ConsultaEntrega")]
    public partial class DT_TM101_Consulta_Entrega_RespItem1 : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string tYPEField;
        
        private string idField;
        
        private string nUMBERField;
        
        private string mESSAGEField;
        
        private string lOG_NOField;
        
        private string lOG_MSG_NOField;
        
        private string mESSAGE_V1Field;
        
        private string mESSAGE_V2Field;
        
        private string mESSAGE_V3Field;
        
        private string mESSAGE_V4Field;
        
        private string pARAMETERField;
        
        private string rOWField;
        
        private string fIELDField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string TYPE {
            get {
                return this.tYPEField;
            }
            set {
                this.tYPEField = value;
                this.RaisePropertyChanged("TYPE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string ID {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("ID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string NUMBER {
            get {
                return this.nUMBERField;
            }
            set {
                this.nUMBERField = value;
                this.RaisePropertyChanged("NUMBER");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string MESSAGE {
            get {
                return this.mESSAGEField;
            }
            set {
                this.mESSAGEField = value;
                this.RaisePropertyChanged("MESSAGE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string LOG_NO {
            get {
                return this.lOG_NOField;
            }
            set {
                this.lOG_NOField = value;
                this.RaisePropertyChanged("LOG_NO");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string LOG_MSG_NO {
            get {
                return this.lOG_MSG_NOField;
            }
            set {
                this.lOG_MSG_NOField = value;
                this.RaisePropertyChanged("LOG_MSG_NO");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string MESSAGE_V1 {
            get {
                return this.mESSAGE_V1Field;
            }
            set {
                this.mESSAGE_V1Field = value;
                this.RaisePropertyChanged("MESSAGE_V1");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string MESSAGE_V2 {
            get {
                return this.mESSAGE_V2Field;
            }
            set {
                this.mESSAGE_V2Field = value;
                this.RaisePropertyChanged("MESSAGE_V2");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public string MESSAGE_V3 {
            get {
                return this.mESSAGE_V3Field;
            }
            set {
                this.mESSAGE_V3Field = value;
                this.RaisePropertyChanged("MESSAGE_V3");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public string MESSAGE_V4 {
            get {
                return this.mESSAGE_V4Field;
            }
            set {
                this.mESSAGE_V4Field = value;
                this.RaisePropertyChanged("MESSAGE_V4");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=10)]
        public string PARAMETER {
            get {
                return this.pARAMETERField;
            }
            set {
                this.pARAMETERField = value;
                this.RaisePropertyChanged("PARAMETER");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=11)]
        public string ROW {
            get {
                return this.rOWField;
            }
            set {
                this.rOWField = value;
                this.RaisePropertyChanged("ROW");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=12)]
        public string FIELD {
            get {
                return this.fIELDField;
            }
            set {
                this.fIELDField = value;
                this.RaisePropertyChanged("FIELD");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SI_OA_TM101_Consulta_EntregaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://cydsa.com/PL/TM/TM101/Sender/WebServices/PesoVehiculo_ConsultaEntrega", Order=0)]
        public ObtenerPesoSAP.PartidasMateriales.DT_TM101_Consulta_Entrega_Req MT_TM101_Consulta_Entrega_Req;
        
        public SI_OA_TM101_Consulta_EntregaRequest() {
        }
        
        public SI_OA_TM101_Consulta_EntregaRequest(ObtenerPesoSAP.PartidasMateriales.DT_TM101_Consulta_Entrega_Req MT_TM101_Consulta_Entrega_Req) {
            this.MT_TM101_Consulta_Entrega_Req = MT_TM101_Consulta_Entrega_Req;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SI_OA_TM101_Consulta_EntregaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://cydsa.com/PL/TM/TM101/Sender/WebServices/PesoVehiculo_ConsultaEntrega", Order=0)]
        public ObtenerPesoSAP.PartidasMateriales.DT_TM101_Consulta_Entrega_Resp MT_TM101_Consulta_Entrega_Resp;
        
        public SI_OA_TM101_Consulta_EntregaResponse() {
        }
        
        public SI_OA_TM101_Consulta_EntregaResponse(ObtenerPesoSAP.PartidasMateriales.DT_TM101_Consulta_Entrega_Resp MT_TM101_Consulta_Entrega_Resp) {
            this.MT_TM101_Consulta_Entrega_Resp = MT_TM101_Consulta_Entrega_Resp;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface SI_OA_TM101_Consulta_EntregaChannel : ObtenerPesoSAP.PartidasMateriales.SI_OA_TM101_Consulta_Entrega, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SI_OA_TM101_Consulta_EntregaClient : System.ServiceModel.ClientBase<ObtenerPesoSAP.PartidasMateriales.SI_OA_TM101_Consulta_Entrega>, ObtenerPesoSAP.PartidasMateriales.SI_OA_TM101_Consulta_Entrega {
        
        public SI_OA_TM101_Consulta_EntregaClient() {
        }
        
        public SI_OA_TM101_Consulta_EntregaClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SI_OA_TM101_Consulta_EntregaClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SI_OA_TM101_Consulta_EntregaClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SI_OA_TM101_Consulta_EntregaClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ObtenerPesoSAP.PartidasMateriales.SI_OA_TM101_Consulta_EntregaResponse ObtenerPesoSAP.PartidasMateriales.SI_OA_TM101_Consulta_Entrega.SI_OA_TM101_Consulta_Entrega(ObtenerPesoSAP.PartidasMateriales.SI_OA_TM101_Consulta_EntregaRequest request) {
            return base.Channel.SI_OA_TM101_Consulta_Entrega(request);
        }
        
        public ObtenerPesoSAP.PartidasMateriales.DT_TM101_Consulta_Entrega_Resp SI_OA_TM101_Consulta_Entrega(ObtenerPesoSAP.PartidasMateriales.DT_TM101_Consulta_Entrega_Req MT_TM101_Consulta_Entrega_Req) {
            ObtenerPesoSAP.PartidasMateriales.SI_OA_TM101_Consulta_EntregaRequest inValue = new ObtenerPesoSAP.PartidasMateriales.SI_OA_TM101_Consulta_EntregaRequest();
            inValue.MT_TM101_Consulta_Entrega_Req = MT_TM101_Consulta_Entrega_Req;
            ObtenerPesoSAP.PartidasMateriales.SI_OA_TM101_Consulta_EntregaResponse retVal = ((ObtenerPesoSAP.PartidasMateriales.SI_OA_TM101_Consulta_Entrega)(this)).SI_OA_TM101_Consulta_Entrega(inValue);
            return retVal.MT_TM101_Consulta_Entrega_Resp;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ObtenerPesoSAP.PartidasMateriales.SI_OA_TM101_Consulta_EntregaResponse> ObtenerPesoSAP.PartidasMateriales.SI_OA_TM101_Consulta_Entrega.SI_OA_TM101_Consulta_EntregaAsync(ObtenerPesoSAP.PartidasMateriales.SI_OA_TM101_Consulta_EntregaRequest request) {
            return base.Channel.SI_OA_TM101_Consulta_EntregaAsync(request);
        }
        
        public System.Threading.Tasks.Task<ObtenerPesoSAP.PartidasMateriales.SI_OA_TM101_Consulta_EntregaResponse> SI_OA_TM101_Consulta_EntregaAsync(ObtenerPesoSAP.PartidasMateriales.DT_TM101_Consulta_Entrega_Req MT_TM101_Consulta_Entrega_Req) {
            ObtenerPesoSAP.PartidasMateriales.SI_OA_TM101_Consulta_EntregaRequest inValue = new ObtenerPesoSAP.PartidasMateriales.SI_OA_TM101_Consulta_EntregaRequest();
            inValue.MT_TM101_Consulta_Entrega_Req = MT_TM101_Consulta_Entrega_Req;
            return ((ObtenerPesoSAP.PartidasMateriales.SI_OA_TM101_Consulta_Entrega)(this)).SI_OA_TM101_Consulta_EntregaAsync(inValue);
        }
    }
}
