//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ObtenerPesoSAP.EnviaPesos {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://cydsa.com/PL/TM/TM101/Receiver/WebServices/PesoVehiculo", ConfigurationName="EnviaPesos.SI_OA_Peso_Vehiculo")]
    public interface SI_OA_Peso_Vehiculo {
        
        // CODEGEN: Generating message contract since the operation SI_OA_Peso_Vehiculo is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="http://sap.com/xi/WebService/soap1.1", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        ObtenerPesoSAP.EnviaPesos.SI_OA_Peso_VehiculoResponse SI_OA_Peso_Vehiculo(ObtenerPesoSAP.EnviaPesos.SI_OA_Peso_VehiculoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://sap.com/xi/WebService/soap1.1", ReplyAction="*")]
        System.Threading.Tasks.Task<ObtenerPesoSAP.EnviaPesos.SI_OA_Peso_VehiculoResponse> SI_OA_Peso_VehiculoAsync(ObtenerPesoSAP.EnviaPesos.SI_OA_Peso_VehiculoRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://cydsa.com/PL/TM/TM101/Receiver/WebServices/PesoVehiculo")]
    public partial class DT_Peso_Vehiculo : object, System.ComponentModel.INotifyPropertyChanged {
        
        private DT_Peso_VehiculoData dataField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public DT_Peso_VehiculoData data {
            get {
                return this.dataField;
            }
            set {
                this.dataField = value;
                this.RaisePropertyChanged("data");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://cydsa.com/PL/TM/TM101/Receiver/WebServices/PesoVehiculo")]
    public partial class DT_Peso_VehiculoData : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string vehicle_NumberField;
        
        private string weight_InitialField;
        
        private string weight_FinalField;
        
        private string economic_NumberField;
        
        private string licence_PlateField;
        
        private string driver_NameField;
        
        private string carriage_NumberField;
        
        private string check_InField;
        
        private string load_StartField;
        
        private string load_EndField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string Vehicle_Number {
            get {
                return this.vehicle_NumberField;
            }
            set {
                this.vehicle_NumberField = value;
                this.RaisePropertyChanged("Vehicle_Number");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string Weight_Initial {
            get {
                return this.weight_InitialField;
            }
            set {
                this.weight_InitialField = value;
                this.RaisePropertyChanged("Weight_Initial");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string Weight_Final {
            get {
                return this.weight_FinalField;
            }
            set {
                this.weight_FinalField = value;
                this.RaisePropertyChanged("Weight_Final");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string Economic_Number {
            get {
                return this.economic_NumberField;
            }
            set {
                this.economic_NumberField = value;
                this.RaisePropertyChanged("Economic_Number");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string Licence_Plate {
            get {
                return this.licence_PlateField;
            }
            set {
                this.licence_PlateField = value;
                this.RaisePropertyChanged("Licence_Plate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string Driver_Name {
            get {
                return this.driver_NameField;
            }
            set {
                this.driver_NameField = value;
                this.RaisePropertyChanged("Driver_Name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string Carriage_Number {
            get {
                return this.carriage_NumberField;
            }
            set {
                this.carriage_NumberField = value;
                this.RaisePropertyChanged("Carriage_Number");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string Check_In {
            get {
                return this.check_InField;
            }
            set {
                this.check_InField = value;
                this.RaisePropertyChanged("Check_In");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public string Load_Start {
            get {
                return this.load_StartField;
            }
            set {
                this.load_StartField = value;
                this.RaisePropertyChanged("Load_Start");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public string Load_End {
            get {
                return this.load_EndField;
            }
            set {
                this.load_EndField = value;
                this.RaisePropertyChanged("Load_End");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://cydsa.com/PL/TM/TM101/Receiver/WebServices/PesoVehiculo")]
    public partial class DT_Return_Peso_VehiculoItem : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string tYPEField;
        
        private string idField;
        
        private string nUMBERField;
        
        private string mESSAGEField;
        
        private string lOG_NOField;
        
        private string lOG_MSG_NOField;
        
        private string mESSAGE_V1Field;
        
        private string mESSAGE_V2Field;
        
        private string mESSAGE_V3Field;
        
        private string mESSAGE_V4Field;
        
        private string pARAMETERField;
        
        private string rOWField;
        
        private string fIELDField;
        
        private string sYSTEMField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string TYPE {
            get {
                return this.tYPEField;
            }
            set {
                this.tYPEField = value;
                this.RaisePropertyChanged("TYPE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string ID {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("ID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string NUMBER {
            get {
                return this.nUMBERField;
            }
            set {
                this.nUMBERField = value;
                this.RaisePropertyChanged("NUMBER");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string MESSAGE {
            get {
                return this.mESSAGEField;
            }
            set {
                this.mESSAGEField = value;
                this.RaisePropertyChanged("MESSAGE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string LOG_NO {
            get {
                return this.lOG_NOField;
            }
            set {
                this.lOG_NOField = value;
                this.RaisePropertyChanged("LOG_NO");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string LOG_MSG_NO {
            get {
                return this.lOG_MSG_NOField;
            }
            set {
                this.lOG_MSG_NOField = value;
                this.RaisePropertyChanged("LOG_MSG_NO");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string MESSAGE_V1 {
            get {
                return this.mESSAGE_V1Field;
            }
            set {
                this.mESSAGE_V1Field = value;
                this.RaisePropertyChanged("MESSAGE_V1");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string MESSAGE_V2 {
            get {
                return this.mESSAGE_V2Field;
            }
            set {
                this.mESSAGE_V2Field = value;
                this.RaisePropertyChanged("MESSAGE_V2");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public string MESSAGE_V3 {
            get {
                return this.mESSAGE_V3Field;
            }
            set {
                this.mESSAGE_V3Field = value;
                this.RaisePropertyChanged("MESSAGE_V3");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public string MESSAGE_V4 {
            get {
                return this.mESSAGE_V4Field;
            }
            set {
                this.mESSAGE_V4Field = value;
                this.RaisePropertyChanged("MESSAGE_V4");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=10)]
        public string PARAMETER {
            get {
                return this.pARAMETERField;
            }
            set {
                this.pARAMETERField = value;
                this.RaisePropertyChanged("PARAMETER");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=11)]
        public string ROW {
            get {
                return this.rOWField;
            }
            set {
                this.rOWField = value;
                this.RaisePropertyChanged("ROW");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=12)]
        public string FIELD {
            get {
                return this.fIELDField;
            }
            set {
                this.fIELDField = value;
                this.RaisePropertyChanged("FIELD");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=13)]
        public string SYSTEM {
            get {
                return this.sYSTEMField;
            }
            set {
                this.sYSTEMField = value;
                this.RaisePropertyChanged("SYSTEM");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SI_OA_Peso_VehiculoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://cydsa.com/PL/TM/TM101/Receiver/WebServices/PesoVehiculo", Order=0)]
        public ObtenerPesoSAP.EnviaPesos.DT_Peso_Vehiculo MT_Peso_Vehiculo;
        
        public SI_OA_Peso_VehiculoRequest() {
        }
        
        public SI_OA_Peso_VehiculoRequest(ObtenerPesoSAP.EnviaPesos.DT_Peso_Vehiculo MT_Peso_Vehiculo) {
            this.MT_Peso_Vehiculo = MT_Peso_Vehiculo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SI_OA_Peso_VehiculoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://cydsa.com/PL/TM/TM101/Receiver/WebServices/PesoVehiculo", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public ObtenerPesoSAP.EnviaPesos.DT_Return_Peso_VehiculoItem[] MT_Return_Peso_Vehiculo;
        
        public SI_OA_Peso_VehiculoResponse() {
        }
        
        public SI_OA_Peso_VehiculoResponse(ObtenerPesoSAP.EnviaPesos.DT_Return_Peso_VehiculoItem[] MT_Return_Peso_Vehiculo) {
            this.MT_Return_Peso_Vehiculo = MT_Return_Peso_Vehiculo;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface SI_OA_Peso_VehiculoChannel : ObtenerPesoSAP.EnviaPesos.SI_OA_Peso_Vehiculo, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SI_OA_Peso_VehiculoClient : System.ServiceModel.ClientBase<ObtenerPesoSAP.EnviaPesos.SI_OA_Peso_Vehiculo>, ObtenerPesoSAP.EnviaPesos.SI_OA_Peso_Vehiculo {
        
        public SI_OA_Peso_VehiculoClient() {
        }
        
        public SI_OA_Peso_VehiculoClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SI_OA_Peso_VehiculoClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SI_OA_Peso_VehiculoClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SI_OA_Peso_VehiculoClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ObtenerPesoSAP.EnviaPesos.SI_OA_Peso_VehiculoResponse ObtenerPesoSAP.EnviaPesos.SI_OA_Peso_Vehiculo.SI_OA_Peso_Vehiculo(ObtenerPesoSAP.EnviaPesos.SI_OA_Peso_VehiculoRequest request) {
            return base.Channel.SI_OA_Peso_Vehiculo(request);
        }
        
        public ObtenerPesoSAP.EnviaPesos.DT_Return_Peso_VehiculoItem[] SI_OA_Peso_Vehiculo(ObtenerPesoSAP.EnviaPesos.DT_Peso_Vehiculo MT_Peso_Vehiculo) {
            ObtenerPesoSAP.EnviaPesos.SI_OA_Peso_VehiculoRequest inValue = new ObtenerPesoSAP.EnviaPesos.SI_OA_Peso_VehiculoRequest();
            inValue.MT_Peso_Vehiculo = MT_Peso_Vehiculo;
            ObtenerPesoSAP.EnviaPesos.SI_OA_Peso_VehiculoResponse retVal = ((ObtenerPesoSAP.EnviaPesos.SI_OA_Peso_Vehiculo)(this)).SI_OA_Peso_Vehiculo(inValue);
            return retVal.MT_Return_Peso_Vehiculo;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ObtenerPesoSAP.EnviaPesos.SI_OA_Peso_VehiculoResponse> ObtenerPesoSAP.EnviaPesos.SI_OA_Peso_Vehiculo.SI_OA_Peso_VehiculoAsync(ObtenerPesoSAP.EnviaPesos.SI_OA_Peso_VehiculoRequest request) {
            return base.Channel.SI_OA_Peso_VehiculoAsync(request);
        }
        
        public System.Threading.Tasks.Task<ObtenerPesoSAP.EnviaPesos.SI_OA_Peso_VehiculoResponse> SI_OA_Peso_VehiculoAsync(ObtenerPesoSAP.EnviaPesos.DT_Peso_Vehiculo MT_Peso_Vehiculo) {
            ObtenerPesoSAP.EnviaPesos.SI_OA_Peso_VehiculoRequest inValue = new ObtenerPesoSAP.EnviaPesos.SI_OA_Peso_VehiculoRequest();
            inValue.MT_Peso_Vehiculo = MT_Peso_Vehiculo;
            return ((ObtenerPesoSAP.EnviaPesos.SI_OA_Peso_Vehiculo)(this)).SI_OA_Peso_VehiculoAsync(inValue);
        }
    }
}
