
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace ObtenerPesoSAP.Models
{

    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    public partial class CPCatProcesos
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public CPCatProcesos()
    {

        this.CPLogDeProcesos = new HashSet<CPLogDeProcesos>();

    }


    public int CPIdProceso { get; set; }
        [DisplayName("Proceso")]
        public string CPDescripcion { get; set; }

    public Nullable<System.DateTime> CPFechaAlta { get; set; }

    public Nullable<int> CPUsuarioAlta { get; set; }

    public Nullable<System.DateTime> CPFechaCambio { get; set; }

    public Nullable<int> CPUsuarioCambio { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<CPLogDeProcesos> CPLogDeProcesos { get; set; }

}

}
