
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace ObtenerPesoSAP.Models
{

    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    public partial class CPCatEmpresas
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public CPCatEmpresas()
    {

        this.CPAutorizaciones = new HashSet<CPAutorizaciones>();

        this.CPCatMateriales = new HashSet<CPCatMateriales>();

        this.CPPartidas = new HashSet<CPPartidas>();

        this.CPPartidas1 = new HashSet<CPPartidas>();

        this.CPPermisosPlantas = new HashSet<CPPermisosPlantas>();

        this.CPLogDeProcesos = new HashSet<CPLogDeProcesos>();

        this.CPBitacora = new HashSet<CPBitacora>();

    }


        [DisplayName("Planta")]
        public int CPIdEmpresa { get; set; }
        [DisplayName("Numero de Empresa")]
        public int CPIdCia { get; set; }
        public bool checkeado { get; set; }
        [DisplayName("Numero de Planta")]
        public int CPIdPlanta { get; set; }
        [DisplayName("Descripcion")]
        public string CPDescripcionEmpresa { get; set; }
        public Nullable<System.DateTime> CPFechaAlta { get; set; }

        public Nullable<int> CPUsuarioAlta { get; set; }
        [DisplayName("Fecha de Usuario")]
        public Nullable<System.DateTime> CPFechaCambio { get; set; }
        [DisplayName("Usuario que hizo el cambio")]
        public Nullable<int> CPUsuarioCambio { get; set; }
        [DisplayName("Forma de Captura")]
        public Nullable<int> CPIdTipoCaptura { get; set; }


        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<CPAutorizaciones> CPAutorizaciones { get; set; }

    public virtual CPCatTipoCaptura CPCatTipoCaptura { get; set; }

    public virtual CPUsuario CPUsuario { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<CPCatMateriales> CPCatMateriales { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<CPPartidas> CPPartidas { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<CPPartidas> CPPartidas1 { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<CPPermisosPlantas> CPPermisosPlantas { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<CPLogDeProcesos> CPLogDeProcesos { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<CPBitacora> CPBitacora { get; set; }

}

}
