
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace ObtenerPesoSAP.Models
{

using System;
    using System.Collections.Generic;
    
public partial class CPCatTiposDeVehiculos
{

    public int CPIdTipoVehiculo { get; set; }

    public string CPDescripcionVehiculo { get; set; }

    public Nullable<int> CPCapacidad { get; set; }

    public Nullable<int> CPIdUnidadMedida { get; set; }

    public Nullable<System.DateTime> CPFechaAlta { get; set; }

    public Nullable<int> CPUsuarioAlta { get; set; }

    public Nullable<System.DateTime> CPFechaCambio { get; set; }

    public Nullable<int> CPUsuarioCambio { get; set; }



    public virtual CPCatUnidades CPCatUnidades { get; set; }

}

}
