
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace ObtenerPesoSAP.Models
{

    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    public partial class CPCatTipoCaptura
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public CPCatTipoCaptura()
    {

        this.CPCatEmpresas = new HashSet<CPCatEmpresas>();

        this.CPPermisosPlantas = new HashSet<CPPermisosPlantas>();

    }

        [DisplayName("Tipo de Captura")]
        public int CPIdTipoCaptura { get; set; }

    public string CPDescripcion { get; set; }

    public Nullable<System.DateTime> CPFechaAlta { get; set; }

    public Nullable<int> CPUsuarioAlta { get; set; }

    public Nullable<System.DateTime> CPFechaCambio { get; set; }

    public Nullable<int> CPUsuarioCambio { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<CPCatEmpresas> CPCatEmpresas { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<CPPermisosPlantas> CPPermisosPlantas { get; set; }

}

}
