
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace ObtenerPesoSAP.Models
{

    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    public partial class CPCatMensajesSAP
{

        public int CPIdMsj { get; set; }
        public Nullable<int> CPIdMsjSAP { get; set; }
        [DisplayName("Parte del mensaje proveniente de SAP")]
        public string CPDescripcionMsjSAP { get; set; }
        [DisplayName("Mensaje anexo a desplegar")]
        public string CPTextoAnexo { get; set; }
        public int CPRol_id { get; set; }
        public Nullable<System.DateTime> CPFechaAlta { get; set; }
        public Nullable<int> CPUsuarioAlta { get; set; }
        [DisplayName("Fecha Cambio")]
        public Nullable<System.DateTime> CPFechaCambio { get; set; }
        public Nullable<int> CPUsuarioCambio { get; set; }


        public virtual CPRol CPRol { get; set; }

    public virtual CPUsuario CPUsuario { get; set; }

    public virtual CPUsuario CPUsuario1 { get; set; }

}

}
