
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace ObtenerPesoSAP.Models
{

using System;
    using System.Collections.Generic;
    
public partial class CPPartidas
{

    public int CPId { get; set; }

    public int CPIdEmpresa { get; set; }

    public Nullable<decimal> CPIdTransporte { get; set; }

    public Nullable<decimal> CPIdDocumento { get; set; }

    public Nullable<double> CPPesoRequerido { get; set; }

    public string CPIdCodigo { get; set; }

    public string CPIdMaterial { get; set; }

    public string CPDescripcion { get; set; }

    public Nullable<int> CPIdUnidadMedida { get; set; }

    public Nullable<int> CPPartida { get; set; }

    public Nullable<System.DateTime> CPFecha { get; set; }

    public int CPIdUsuario { get; set; }

    public Nullable<int> CPEstatus { get; set; }



    public virtual CPCatEmpresas CPCatEmpresas { get; set; }

    public virtual CPCatEmpresas CPCatEmpresas1 { get; set; }

    public virtual CPCatUnidades CPCatUnidades { get; set; }

    public virtual CPCatUnidades CPCatUnidades1 { get; set; }

    public virtual CPUsuario CPUsuario { get; set; }

    public virtual CPUsuario CPUsuario1 { get; set; }

}

}
