
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace ObtenerPesoSAP.Models
{

    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    public partial class CPPermisosPlantas
{


        public int CPId { get; set; }
        [DisplayName("Planta")]
        public int CPIdEmpresa { get; set; }
        [DisplayName("Usuario")]
        public int CPIdUsuario { get; set; }
        public Nullable<System.DateTime> CPFechaAlta { get; set; }
        public Nullable<int> CPUsuarioAlta { get; set; }
        public Nullable<System.DateTime> CPFechaCambio { get; set; }
        public Nullable<int> CPUsuarioCambio { get; set; }
        public Nullable<bool> CPPlantaDefault { get; set; }
        public Nullable<int> CPIdTipoCaptura { get; set; }




        public virtual CPCatEmpresas CPCatEmpresas { get; set; }

    public virtual CPCatTipoCaptura CPCatTipoCaptura { get; set; }

    public virtual CPUsuario CPUsuario { get; set; }

}

}
