
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace ObtenerPesoSAP.Models
{

    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class CPUsuario
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public CPUsuario()
    {

        this.CPAutorizaciones = new HashSet<CPAutorizaciones>();

        this.CPCatEmpresas = new HashSet<CPCatEmpresas>();

        this.CPCatMateriales = new HashSet<CPCatMateriales>();

        this.CPCatMateriales1 = new HashSet<CPCatMateriales>();

        this.CPPartidas = new HashSet<CPPartidas>();

        this.CPPartidas1 = new HashSet<CPPartidas>();

        this.CPPermisosPlantas = new HashSet<CPPermisosPlantas>();

        this.CPCatMensajesSAP = new HashSet<CPCatMensajesSAP>();

        this.CPCatMensajesSAP1 = new HashSet<CPCatMensajesSAP>();

        this.CPLogDeProcesos = new HashSet<CPLogDeProcesos>();

        this.CPBitacora = new HashSet<CPBitacora>();

        this.CPBitacora1 = new HashSet<CPBitacora>();

    }


        public int CPIdUsuario { get; set; }
        public int CPRol_id { get; set; }
        [DisplayName("Usuario")]
        public string CPNombreUsuario { get; set; }
        [DisplayName("Correo")]
        [Required(AllowEmptyStrings = false, ErrorMessage = "El correo no puede ir vacio")]
        public string CPCorreo { get; set; }
        [DisplayName("Contraseña")]
        public string CPPassword { get; set; }
        public Nullable<bool> Estatus { get; set; }


        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<CPAutorizaciones> CPAutorizaciones { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<CPCatEmpresas> CPCatEmpresas { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<CPCatMateriales> CPCatMateriales { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<CPCatMateriales> CPCatMateriales1 { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<CPPartidas> CPPartidas { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<CPPartidas> CPPartidas1 { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<CPPermisosPlantas> CPPermisosPlantas { get; set; }

    public virtual CPRol CPRol { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<CPCatMensajesSAP> CPCatMensajesSAP { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<CPCatMensajesSAP> CPCatMensajesSAP1 { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<CPLogDeProcesos> CPLogDeProcesos { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<CPBitacora> CPBitacora { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<CPBitacora> CPBitacora1 { get; set; }

}

}
